#!/usr/bin/env python3
"""Regenerate everything that is derived from the meta.yaml files.

    python scripts/build_index.py            # rewrite the generated regions
    python scripts/build_index.py --check    # only report whether they are up to date (used by CI)

* the metadata table at the top of every problem page (between the meta markers)
* the problem tables in README.md / README.zh.md (between the index markers)
* ROADMAP.md / ROADMAP.zh.md (whole files, from scripts/roadmap.yaml)

Run it after editing any meta.yaml or scripts/roadmap.yaml. It only rewrites generated
regions, so hand-written text is never touched.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

from _lib import (CATEGORIES, LABELS, LANGS, README, ROOT, Problem, load_problems, meta_table, replace_block,
                  roles_label)

ROADMAP = {"en": "ROADMAP.md", "zh": "ROADMAP.zh.md"}


def index_row(p: Problem, lang: str, n: int) -> str:
    L = LABELS[lang]
    m = p.meta
    link = f"[{p.title(lang)}]({p.rel}/{README[lang]})"
    return "| " + " | ".join([
        str(n), link, L["frequency"][m["frequency"]], L["difficulty"][m.get("difficulty")],
        roles_label(m, lang), ", ".join(m["topics"]),
    ]) + " |"


def build_index(problems: list[Problem], lang: str) -> str:
    L = LABELS[lang]
    c = L["cols"]
    out: list[str] = []
    for cat in CATEGORIES:
        rows = sorted((p for p in problems if p.meta["category"] == cat), key=Problem.sort_key)
        out.append(f"### {L['category'][cat]} ({len(rows)})")
        out.append("")
        out.append(f"| # | {c['problem']} | {c['frequency']} | {c['difficulty']} | {c['roles']} | {c['topics']} |")
        out.append("| ---: | --- | --- | --- | --- | --- |")
        out += [index_row(p, lang, i) for i, p in enumerate(rows, 1)]
        out.append("")
    return "\n".join(out)


def build_roadmap(problems: list[Problem], lang: str) -> str:
    L = LABELS[lang]
    c = L["cols"]
    by_rel = {p.rel: p for p in problems}
    spec = yaml.safe_load((ROOT / "scripts" / "roadmap.yaml").read_text(encoding="utf-8"))
    zh = lang == "zh"
    out = ["<!-- Generated by scripts/build_index.py from scripts/roadmap.yaml. Do not edit by hand. -->", ""]
    out.append(f"# {spec['title_zh'] if zh else spec['title']}")
    out.append("")
    out.append(f"[English]({ROADMAP['en']}) · [中文]({ROADMAP['zh']})")
    out.append("")
    out.append(spec["intro_zh"] if zh else spec["intro"])
    out.append("")

    def table(rows: list[Problem]) -> list[str]:
        t = [f"| # | {c['problem']} | {c['frequency']} | {c['difficulty']} | {c['summary']} |",
             "| ---: | --- | --- | --- | --- |"]
        for i, p in enumerate(rows, 1):
            m = p.meta
            t.append(f"| {i} | [{p.title(lang)}]({p.rel}/{README[lang]}) | {L['frequency'][m['frequency']]} "
                     f"| {L['difficulty'][m.get('difficulty')]} | {p.summary(lang)} |")
        return t

    for track in spec["tracks"]:
        out.append(f"## {track['title_zh'] if zh else track['title']}")
        out.append("")
        out.append((track.get("intro_zh") if zh else track.get("intro")) or "")
        out.append("")
        if "stages" in track:
            for stage in track["stages"]:
                out.append(f"### {stage['name_zh'] if zh else stage['name']}")
                out.append("")
                note = stage.get("note_zh") if zh else stage.get("note")
                if note:
                    out += [note, ""]
                missing = [r for r in stage["items"] if r not in by_rel]
                if missing:
                    raise SystemExit(f"scripts/roadmap.yaml refers to unknown problems: {missing}")
                out += table([by_rel[r] for r in stage["items"]])
                out.append("")
        else:
            roles = set(track["auto_roles"])
            rows = sorted((p for p in problems if roles & set(p.meta["roles"])),
                          key=lambda p: (p.sort_key()[0], CATEGORIES.index(p.meta["category"]), p.meta["order"]))
            out += table(rows)
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def generated_files(problems: list[Problem]) -> dict[Path, str]:
    """Every file this script owns, mapped to the content it should have."""
    want: dict[Path, str] = {}
    for p in problems:
        for lang in LANGS:
            page = p.path / README[lang]
            want[page] = replace_block(page.read_text(encoding="utf-8"), "meta", meta_table(p, lang))
    for lang in LANGS:
        home = ROOT / README[lang]
        want[home] = replace_block(home.read_text(encoding="utf-8"), "index", build_index(problems, lang))
        want[ROOT / ROADMAP[lang]] = build_roadmap(problems, lang)
    return want


def main() -> int:
    check = "--check" in sys.argv[1:]
    problems = load_problems()
    stale = [f for f, text in generated_files(problems).items()
             if not f.exists() or f.read_text(encoding="utf-8") != text]
    if check:
        for f in stale:
            print(f"✗ {f.relative_to(ROOT)} is out of date")
        if stale:
            print("run python scripts/build_index.py and commit the result")
            return 1
        print(f"✓ {len(problems)} problems, generated tables are up to date")
        return 0
    for f, text in generated_files(problems).items():
        if f in stale:
            f.write_text(text, encoding="utf-8")
    print(f"{len(problems)} problems · {len(stale)} file(s) rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
